#!/bin/bash 

VOL="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
MUTE="$(pactl get-sink-mute @DEFAULT_SINK@ | tail -c 5)"

if [ $MUTE == "sim" ]
then
   echo "M"
else
   echo "$VOL%"
fi

